name: Deploy
on:
  push:
    branches: ['*'] # Do not run on tags
jobs:
  build:
    name: Builder Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Extract git context
        id: context
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=short_sha;]$(echo ${GITHUB_SHA:0:7})"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Google Cloud SDK
        uses: mathrix-education/setup-gcloud@0.1.2
        with:
          project: ${{ secrets.GCLOUD_PROJECT }}
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: true
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
          extension-csv: mbstring, gmp
          coverage: none
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Build Docker Image
        run: docker build -t eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/good-plans-api:${{ steps.context.outputs.short_sha }} .
      - name: Push Docker Image to Google Cloud Container Registry
        run: docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/good-plans-api:${{ steps.context.outputs.short_sha }}
      - name: Push to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag \
            eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/good-plans-api:${{ steps.context.outputs.short_sha }} \
            mathrix/good-plans-api:${{ steps.context.outputs.short_sha }}
          docker push mathrix/good-plans-api:${{ steps.context.outputs.short_sha }}
  deploy:
    name: Deploy Docker image on Google Cloud Run
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Extract git context
        id: context
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=short_sha;]$(echo ${GITHUB_SHA:0:7})"
      - name: Setup Google Cloud SDK
        uses: mathrix-education/setup-gcloud@0.1.2
        with:
          project: ${{ secrets.GCLOUD_PROJECT }}
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy on Google Cloud Run
        if: contains('master,dev,next', steps.extract_branch.outputs.branch)
        run: |
          gcloud run deploy good-plans-api-${{ steps.context.outputs.branch }} \
            --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/good-plans-api:${{ steps.context.outputs.short_sha }} \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated
